Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,275 +4,279 @@
 #
 # Build Matrix
 #
-matrix:
-  - os: linux
-    dist: bionic
-    language: c
 
-    git:
-      - depth: 1
+- arch:
+    - arm64
+    - amd64
+        matrix:
+          - os: linux
+            dist: bionic
+            language: c
 
-    compiler: gcc
-    env: DESC="linux/gcc build and test"
+            git:
+              - depth: 1
 
-    addons:
-      apt:
-        packages:
-          - build-essential
-          - cmake
-          - net-tools
-          - python-pip
-          - python-setuptools
-          - python3-pip
-          - python3-setuptools
-          - valgrind
-          - psmisc
+            compiler: gcc
+            env: DESC="linux/gcc build and test"
 
-    before_script:
-      - cd ${TRAVIS_BUILD_DIR}
-      - mkdir debug
-      - cd debug
+            addons:
+              apt:
+                packages:
+                  - build-essential
+                  - cmake
+                  - net-tools
+                  - python-pip
+                  - python-setuptools
+                  - python3-pip
+                  - python3-setuptools
+                  - valgrind
+                  - psmisc
 
-    script:
-      - cmake .. > /dev/null
-      - make > /dev/null
+            before_script:
+              - cd ${TRAVIS_BUILD_DIR}
+              - mkdir debug
+              - cd debug
 
-    after_success:
-      - travis_wait 20
-      - |-
-        case $TRAVIS_OS_NAME in
-          linux)
-          cd ${TRAVIS_BUILD_DIR}/debug
-          make install > /dev/null || travis_terminate $?
+            script:
+              - cmake .. > /dev/null
+              - make > /dev/null
 
-          pip install numpy
-          pip install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python2/
-          pip3 install numpy
-          pip3 install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python3/
+            after_success:
+              - travis_wait 20
+              - |-
+                case $TRAVIS_OS_NAME in
+                  linux)
+                  cd ${TRAVIS_BUILD_DIR}/debug
+                  make install > /dev/null || travis_terminate $?
 
-          cd ${TRAVIS_BUILD_DIR}/tests
-          ./test-all.sh smoke || travis_terminate $?
+                  pip install numpy
+                  pip install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python2/
+                  pip3 install numpy
+                  pip3 install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python3/
 
-          cd ${TRAVIS_BUILD_DIR}/tests/pytest
-          ./valgrind-test.sh 2>&1 > mem-error-out.log
-          sleep 1
+                  cd ${TRAVIS_BUILD_DIR}/tests
+                  ./test-all.sh smoke || travis_terminate $?
 
-          # Color setting
-          RED='\033[0;31m'
-          GREEN='\033[1;32m'
-          GREEN_DARK='\033[0;32m'
-          GREEN_UNDERLINE='\033[4;32m'
-          NC='\033[0m'
+                  cd ${TRAVIS_BUILD_DIR}/tests/pytest
+                  ./valgrind-test.sh 2>&1 > mem-error-out.log
+                  sleep 1
 
-          grep 'start to execute\|ERROR SUMMARY' mem-error-out.log|grep -v 'grep'|uniq|tee uniq-mem-error-out.log
+                  # Color setting
+                  RED='\033[0;31m'
+                  GREEN='\033[1;32m'
+                  GREEN_DARK='\033[0;32m'
+                  GREEN_UNDERLINE='\033[4;32m'
+                  NC='\033[0m'
 
-          for memError in `grep 'ERROR SUMMARY' uniq-mem-error-out.log | awk '{print $4}'`
-          do
-            if [ -n "$memError" ]; then
-              if [ "$memError" -gt 12 ]; then
-                echo -e "${RED} ## Memory errors number valgrind reports is $memError.\
-                         More than our threshold! ## ${NC}"
-                travis_terminate $memError
-              fi
-            fi
-          done
+                  grep 'start to execute\|ERROR SUMMARY' mem-error-out.log|grep -v 'grep'|uniq|tee uniq-mem-error-out.log
 
-          grep 'start to execute\|definitely lost:' mem-error-out.log|grep -v 'grep'|uniq|tee uniq-definitely-lost-out.log
-          for defiMemError in `grep 'definitely lost:' uniq-definitely-lost-out.log | awk '{print $7}'`
-          do
-            if [ -n "$defiMemError" ]; then
-              if [ "$defiMemError" -gt 13 ]; then
-                echo -e "${RED} ## Memory errors number valgrind reports \
-                         Definitely lost is $defiMemError. More than our threshold! ## ${NC}"
-                travis_terminate $defiMemError
-              fi
-            fi
-          done
+                  for memError in `grep 'ERROR SUMMARY' uniq-mem-error-out.log | awk '{print $4}'`
+                  do
+                    if [ -n "$memError" ]; then
+                      if [ "$memError" -gt 12 ]; then
+                        echo -e "${RED} ## Memory errors number valgrind reports is $memError.\
+                                 More than our threshold! ## ${NC}"
+                        travis_terminate $memError
+                      fi
+                    fi
+                  done
 
-          ;;
-        esac
+                  grep 'start to execute\|definitely lost:' mem-error-out.log|grep -v 'grep'|uniq|tee uniq-definitely-lost-out.log
+                  for defiMemError in `grep 'definitely lost:' uniq-definitely-lost-out.log | awk '{print $7}'`
+                  do
+                    if [ -n "$defiMemError" ]; then
+                      if [ "$defiMemError" -gt 13 ]; then
+                        echo -e "${RED} ## Memory errors number valgrind reports \
+                                 Definitely lost is $defiMemError. More than our threshold! ## ${NC}"
+                        travis_terminate $defiMemError
+                      fi
+                    fi
+                  done
 
-  - os: linux
-    dist: bionic
-    language: c
-    compiler: gcc
-    env: COVERITY_SCAN=true
-    git:
-      - depth: 1
+                  ;;
+                esac
 
-    script:
-      - echo "this job is for coverity scan"
+          - os: linux
+            dist: bionic
+            language: c
+            compiler: gcc
+            env: COVERITY_SCAN=true
+            git:
+              - depth: 1
 
-    addons:
-      coverity_scan:
-        # GitHub project metadata
-        # ** specific to your project **
-        project:
-          name: TDengine
-          version: 2.x
-          description: TDengine
+            script:
+              - echo "this job is for coverity scan"
 
-        # Where email notification of build analysis results will be sent
-        notification_email: sdsang@taosdata.com, slguan@taosdata.com
+            addons:
+              coverity_scan:
+                # GitHub project metadata
+                # ** specific to your project **
+                project:
+                  name: TDengine
+                  version: 2.x
+                  description: TDengine
 
-        # Commands to prepare for build_command
-        # ** likely specific to your build **
-        build_command_prepend: cmake . > /dev/null
+                # Where email notification of build analysis results will be sent
+                notification_email: sdsang@taosdata.com, slguan@taosdata.com
 
-        # The command that will be added as an argument to "cov-build" to compile your project for analysis,
-        # ** likely specific to your build **
-        build_command: make
+                # Commands to prepare for build_command
+                # ** likely specific to your build **
+                build_command_prepend: cmake . > /dev/null
 
-        # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
-        # Take care in resource usage, and consider the build frequency allowances per
-        #   https://scan.coverity.com/faq#frequency
-        branch_pattern: coverity_scan
+                # The command that will be added as an argument to "cov-build" to compile your project for analysis,
+                # ** likely specific to your build **
+                build_command: make
 
-  - os: linux
-    dist: bionic
-    language: c
-    compiler: gcc
-    env: ENV_COVER=true
+                # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
+                # Take care in resource usage, and consider the build frequency allowances per
+                #   https://scan.coverity.com/faq#frequency
+                branch_pattern: coverity_scan
 
-    git:
-      - depth: 1
+          - os: linux
+            dist: bionic
+            language: c
+            compiler: gcc
+            env: ENV_COVER=true
 
-    addons:
-      apt:
-        packages:
-          - build-essential
-          - cmake
-          - net-tools
-          - python-pip
-          - python-setuptools
-          - python3-pip
-          - python3-setuptools
-          - lcov
-          - psmisc
+            git:
+              - depth: 1
 
-    before_script:
-      - cd ${TRAVIS_BUILD_DIR}
-      - mkdir debug
-      - cd debug
+            addons:
+              apt:
+                packages:
+                  - build-essential
+                  - cmake
+                  - net-tools
+                  - python-pip
+                  - python-setuptools
+                  - python3-pip
+                  - python3-setuptools
+                  - lcov
+                  - psmisc
 
-    script:
-      - cmake -DCOVER=true .. > /dev/null
-      - make > /dev/null
+            before_script:
+              - cd ${TRAVIS_BUILD_DIR}
+              - mkdir debug
+              - cd debug
 
-    after_success:
-      - |-
-        case $TRAVIS_OS_NAME in
-          linux)
-          cd ${TRAVIS_BUILD_DIR}/debug
-          make install > /dev/null || travis_terminate $?
+            script:
+              - cmake -DCOVER=true .. > /dev/null
+              - make > /dev/null
 
-          pip install numpy
-          pip install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python2/
-          pip3 install numpy
-          pip3 install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python3/
+            after_success:
+              - |-
+                case $TRAVIS_OS_NAME in
+                  linux)
+                  cd ${TRAVIS_BUILD_DIR}/debug
+                  make install > /dev/null || travis_terminate $?
 
-          cd ${TRAVIS_BUILD_DIR}/tests
+                  pip install numpy
+                  pip install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python2/
+                  pip3 install numpy
+                  pip3 install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python3/
 
-          ./test-all.sh smoke COVER
+                  cd ${TRAVIS_BUILD_DIR}/tests
 
-          TEST_RESULT=$?
+                  ./test-all.sh smoke COVER
 
-          pkill taosd
-          sleep 1
+                  TEST_RESULT=$?
 
-          cd ${TRAVIS_BUILD_DIR}
-          lcov -d . --capture --rc lcov_branch_coverage=1 -o coverage.info
-          lcov --remove coverage.info '*/tests/*' '*/test/*' '*/deps/*' '*/plugins/*' -o coverage.info
-          lcov -l --rc lcov_branch_coverage=1 coverage.info || travis_terminate $?
+                  pkill taosd
+                  sleep 1
 
-          gem install coveralls-lcov
+                  cd ${TRAVIS_BUILD_DIR}
+                  lcov -d . --capture --rc lcov_branch_coverage=1 -o coverage.info
+                  lcov --remove coverage.info '*/tests/*' '*/test/*' '*/deps/*' '*/plugins/*' -o coverage.info
+                  lcov -l --rc lcov_branch_coverage=1 coverage.info || travis_terminate $?
 
-          # Color setting
-          RED='\033[0;31m'
-          GREEN='\033[1;32m'
-          GREEN_DARK='\033[0;32m'
-          GREEN_UNDERLINE='\033[4;32m'
-          NC='\033[0m'
+                  gem install coveralls-lcov
 
-          coveralls-lcov coverage.info
-          if [ "$?" -eq "0" ]; then
-            echo -e "${GREEN} ## Uploaded to Coveralls.io! ## ${NC}"
-          else
-            echo -e "${RED} ## Coveralls.io not collect coverage report! ## ${NC} "
-          fi
+                  # Color setting
+                  RED='\033[0;31m'
+                  GREEN='\033[1;32m'
+                  GREEN_DARK='\033[0;32m'
+                  GREEN_UNDERLINE='\033[4;32m'
+                  NC='\033[0m'
 
-          bash <(curl -s https://codecov.io/bash) -y .codecov.yml -f coverage.info
-          if [ "$?" -eq "0" ]; then
-            echo -e "${GREEN} ## Uploaded to Codecov! ## ${NC} "
-          else
-            echo -e "${RED} ## Codecov did not collect coverage report! ## ${NC} "
-          fi
+                  coveralls-lcov coverage.info
+                  if [ "$?" -eq "0" ]; then
+                    echo -e "${GREEN} ## Uploaded to Coveralls.io! ## ${NC}"
+                  else
+                    echo -e "${RED} ## Coveralls.io not collect coverage report! ## ${NC} "
+                  fi
 
-          if [ "$TEST_RESULT" -ne "0" ]; then
-            travis_terminate $?
-          fi
-          ;;
-        esac
+                  bash <(curl -s https://codecov.io/bash) -y .codecov.yml -f coverage.info
+                  if [ "$?" -eq "0" ]; then
+                    echo -e "${GREEN} ## Uploaded to Codecov! ## ${NC} "
+                  else
+                    echo -e "${RED} ## Codecov did not collect coverage report! ## ${NC} "
+                  fi
 
-  - os: linux
-    dist: trusty
-    language: c
-    git:
-      - depth: 1
+                  if [ "$TEST_RESULT" -ne "0" ]; then
+                    travis_terminate $?
+                  fi
+                  ;;
+                esac
 
-    addons:
-      apt:
-        packages:
-          - build-essential
-          - cmake
-    env: 
-      - DESC="trusty/gcc-4.8 build"
+          - os: linux
+            dist: trusty
+            language: c
+            git:
+              - depth: 1
 
-    before_script:
-      - cd ${TRAVIS_BUILD_DIR}
-      - mkdir debug
-      - cd debug
+            addons:
+              apt:
+                packages:
+                  - build-essential
+                  - cmake
+            env: 
+              - DESC="trusty/gcc-4.8 build"
 
-    script:
-      - cmake .. > /dev/null
-      - make > /dev/null
+            before_script:
+              - cd ${TRAVIS_BUILD_DIR}
+              - mkdir debug
+              - cd debug
 
-  - os: linux
-    dist: bionic
-    language: c
-    compiler: clang
-    env: DESC="linux/clang build"
-    git:
-      - depth: 1
+            script:
+              - cmake .. > /dev/null
+              - make > /dev/null
 
-    addons:
-      apt:
-        packages:
-          - build-essential
-          - cmake
+          - os: linux
+            dist: bionic
+            language: c
+            compiler: clang
+            env: DESC="linux/clang build"
+            git:
+              - depth: 1
 
-    before_script:
-      - cd ${TRAVIS_BUILD_DIR}
-      - mkdir debug
-      - cd debug
+            addons:
+              apt:
+                packages:
+                  - build-essential
+                  - cmake
 
-    script:
-      - cmake .. > /dev/null
-      - make > /dev/null
+            before_script:
+              - cd ${TRAVIS_BUILD_DIR}
+              - mkdir debug
+              - cd debug
 
-        #  - os: osx
-        #    language: c
-        #    compiler: clang
-        #    env: DESC="mac/clang build"
-        #    git:
-        #      - depth: 1
-        #    addons:
-        #      homebrew:
-        #        - cmake
-        #
-        #    script:
-        #      - cd ${TRAVIS_BUILD_DIR}
-        #      - mkdir debug
-        #      - cd debug
-        #      - cmake .. > /dev/null
-        #      - make > /dev/null
+            script:
+              - cmake .. > /dev/null
+              - make > /dev/null
+
+                #  - os: osx
+                #    language: c
+                #    compiler: clang
+                #    env: DESC="mac/clang build"
+                #    git:
+                #      - depth: 1
+                #    addons:
+                #      homebrew:
+                #        - cmake
+                #
+                #    script:
+                #      - cd ${TRAVIS_BUILD_DIR}
+                #      - mkdir debug
+                #      - cd debug
+                #      - cmake .. > /dev/null
+                #      - make > /dev/null
